# Generated by Django 4.2.13 on 2024-07-10 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254)),
                ('medicalCond', models.CharField(max_length=100)),
                ('medi_1', models.CharField(max_length=100)),
                ('time_1', models.DateTimeField(default=django.utils.timezone.now)),
                ('medi_2', models.CharField(max_length=100)),
                ('time_2', models.DateTimeField(default=django.utils.timezone.now)),
                ('encoding_vector', models.TextField(default='NULL', max_length=200)),
            ],
        ),
    ]
